### ISSUE TITLE
View Current User's Posts

### ISSUE THREAD

**Issue by tylerghilliard94** [nss-day-cohort-56/rare-client-spanish-inquisition#44]
As an author, I would like to see a list of all the Posts I have written so that I can easily view, edit, delete, publish or unpublish them.

**Given** the user is in the Rare application  
**When** they select the `My Posts` menu option  
**Then** they should be directed to the "My Posts" list page  
**And** the page should display ALL the Posts authored by the logged-in user  
**And** each post in the list should display the title, author and category  
**And** the list should be in order of creation date with the most recent on top

**Comment by moyerga718** [comment]
**Front end**

- [ ] Write getter functions to  get posts by user id - ok, its gon be a component or a filter . cool 

**Back End**

- [ ] Create method to get all posts by one user from db (need to insert test data to db with user_id fk first)
- [ ] Create get route that queries posts by user id
